name: "ðŸ“¦ Pre-Release"

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Compile
        id: linux
        uses: rust-build/rust-build.action@v1.4.4
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          UPLOAD_MODE: none
      - name: Compile
        id: win
        uses: rust-build/rust-build.action@v1.4.4
        with:
          RUSTTARGET: x86_64-pc-windows-gnu
          UPLOAD_MODE: none
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            prerelease: true
            automatic_release_tag: latest
            files: |
              ${{ steps.win.outputs.BUILT_ARCHIVE }}
              ${{ steps.win.outputs.BUILT_CHECKSUM }}
              ${{ steps.linux.outputs.BUILT_ARCHIVE }}
              ${{ steps.linux.outputs.BUILT_CHECKSUM }}
